#!/usr/bin/env bash
#
# PC Remote installer for Raspberry Pi (Zero 2 W / any Pi with USB OTG).
# Run as a NORMAL user (not root) from the repo directory:
#
#     ./install.sh
#
# The script calls sudo itself where needed. Safe to re-run — it is idempotent
# (e.g. to change the password, MAC, or keyboard layout later).

set -euo pipefail

# --- pretty output -----------------------------------------------------------
c_ok()   { printf '\033[32m✓\033[0m %s\n' "$*"; }
c_info() { printf '\033[36m•\033[0m %s\n' "$*"; }
c_warn() { printf '\033[33m!\033[0m %s\n' "$*"; }
c_err()  { printf '\033[31m✗\033[0m %s\n' "$*" >&2; }
die()    { c_err "$*"; exit 1; }

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- sanity ------------------------------------------------------------------
[[ "$(uname -s)" == "Linux" ]] || die "This installer only runs on Raspberry Pi OS (Linux). The USB gadget setup is kernel-level."
[[ "${EUID}" -ne 0 ]] || die "Don't run as root. Run as a normal user: ./install.sh (I'll use sudo myself)."
command -v sudo >/dev/null || die "sudo not found."
command -v python3 >/dev/null || die "python3 not found."

TARGET_USER="$(id -un)"
TARGET_HOME="$HOME"
CFG_DIR="$TARGET_HOME/.config/pc-remote"
APP_DIR="$TARGET_HOME/pc-remote"

echo
c_info "Installing PC Remote for user: $TARGET_USER ($TARGET_HOME)"
echo

# --- 1. configuration questions ----------------------------------------------
# Read existing values so a re-run can offer them as defaults.
OLD_MAC=""; OLD_LAYOUT=""
if [[ -f "$CFG_DIR/config.env" ]]; then
    OLD_MAC="$(sed -n 's/^PC_MAC=//p' "$CFG_DIR/config.env" | head -1)"
    OLD_LAYOUT="$(sed -n 's/^KEYBOARD_LAYOUT=//p' "$CFG_DIR/config.env" | head -1)"
fi

mac_prompt="PC Ethernet MAC (for Wake-on-LAN), e.g. AA:BB:CC:DD:EE:FF"
[[ -n "$OLD_MAC" ]] && mac_prompt="$mac_prompt [Enter = keep $OLD_MAC]"

PC_MAC=""
while true; do
    read -rp "› $mac_prompt: " PC_MAC
    PC_MAC="${PC_MAC:-$OLD_MAC}"
    # dashes -> colons, lowercase -> uppercase
    PC_MAC="$(echo "$PC_MAC" | tr 'a-f-' 'A-F:')"
    if [[ -z "$PC_MAC" ]]; then
        c_warn "Empty MAC — the 'Wake PC' button won't work, the rest will. You can add a MAC later in $CFG_DIR/config.env."
        break
    elif [[ "$PC_MAC" =~ ^([0-9A-F]{2}:){5}[0-9A-F]{2}$ ]]; then
        c_ok "MAC: $PC_MAC"
        break
    else
        c_warn "That doesn't look like a MAC (expected 6 hex pairs). Try again or press Enter to skip."
        OLD_MAC=""
    fi
done

# Keyboard layout active on the Windows side.
DEF_LAYOUT="${OLD_LAYOUT:-pl}"
echo
c_info "Keyboard layout on the Windows side (affects how typed characters land):"
echo "    1) Polish (Programmers) — US base + ą/ć/ł… via AltGr"
echo "    2) US English          — ASCII only"
read -rp "› Choose 1/2 [default: $([[ "$DEF_LAYOUT" == us ]] && echo 2 || echo 1)]: " LAYOUT_CHOICE
case "$LAYOUT_CHOICE" in
    1) KEYBOARD_LAYOUT=pl ;;
    2) KEYBOARD_LAYOUT=us ;;
    "") KEYBOARD_LAYOUT="$DEF_LAYOUT" ;;
    *) c_warn "Unknown choice — using default ($DEF_LAYOUT)."; KEYBOARD_LAYOUT="$DEF_LAYOUT" ;;
esac
c_ok "Keyboard layout: $KEYBOARD_LAYOUT"

read -rp "› Web panel port [5000]: " REMOTE_PORT
REMOTE_PORT="${REMOTE_PORT:-5000}"

echo
c_info "Windows login password (for the '🔑 Log in' button). Optional."
c_info "Typed silently, kept outside the repo in $CFG_DIR/login.secret (chmod 600)."
read -rsp "› Windows password (Enter = skip / keep current): " WIN_PASS; echo

# --- 2. system dependencies --------------------------------------------------
echo
c_info "Installing dependencies (python3-flask, wakeonlan)…"
sudo apt-get update -qq
sudo apt-get install -y -qq python3-flask wakeonlan
c_ok "Dependencies ready."

# --- 3. application files ----------------------------------------------------
mkdir -p "$APP_DIR"
cp "$REPO_DIR/pc-remote/app.py" "$REPO_DIR/pc-remote/hid_keyboard.py" "$APP_DIR/"
c_ok "App installed to $APP_DIR"

# --- 4. config.env + secret --------------------------------------------------
mkdir -p "$CFG_DIR"
chmod 700 "$CFG_DIR"
cat > "$CFG_DIR/config.env" <<EOF
# Generated by install.sh — edit then: sudo systemctl restart pc-remote
PC_MAC=$PC_MAC
REMOTE_HOST=0.0.0.0
REMOTE_PORT=$REMOTE_PORT
KEYBOARD_LAYOUT=$KEYBOARD_LAYOUT
EOF
chmod 600 "$CFG_DIR/config.env"
c_ok "Config written: $CFG_DIR/config.env"

if [[ -n "$WIN_PASS" ]]; then
    printf '%s' "$WIN_PASS" > "$CFG_DIR/login.secret"
    chmod 600 "$CFG_DIR/login.secret"
    c_ok "Password saved (chmod 600)."
elif [[ -f "$CFG_DIR/login.secret" ]]; then
    c_info "Password unchanged (existing file kept)."
else
    c_warn "No password — the 'Log in' button returns 400. Add one later to $CFG_DIR/login.secret."
fi
unset WIN_PASS

# --- 5. USB gadget: config.txt ----------------------------------------------
# config.txt path differs between Pi OS versions.
BOOT_CFG=""
for p in /boot/firmware/config.txt /boot/config.txt; do
    [[ -f "$p" ]] && { BOOT_CFG="$p"; break; }
done

NEED_REBOOT=0
if [[ -z "$BOOT_CFG" ]]; then
    c_warn "Couldn't find config.txt — add 'dtoverlay=dwc2,dr_mode=peripheral' manually."
elif grep -q '^dtoverlay=dwc2,dr_mode=peripheral' "$BOOT_CFG"; then
    c_ok "config.txt: dtoverlay=dwc2 already set ($BOOT_CFG)."
else
    echo 'dtoverlay=dwc2,dr_mode=peripheral' | sudo tee -a "$BOOT_CFG" >/dev/null
    c_ok "Added dtoverlay=dwc2 to $BOOT_CFG"
    NEED_REBOOT=1
fi

# --- 6. gadget script + service ----------------------------------------------
sudo cp "$REPO_DIR/usr-local-bin/hid-gadget.sh" /usr/local/bin/hid-gadget.sh
sudo chmod +x /usr/local/bin/hid-gadget.sh
sudo cp "$REPO_DIR/systemd/hid-gadget.service" /etc/systemd/system/hid-gadget.service
c_ok "HID gadget installed."

# --- 7. panel service (fill user/paths into the template) --------------------
TMP_SVC="$(mktemp)"
sed -e "s|__USER__|$TARGET_USER|g" -e "s|__HOME__|$TARGET_HOME|g" \
    "$REPO_DIR/systemd/pc-remote.service" > "$TMP_SVC"
sudo cp "$TMP_SVC" /etc/systemd/system/pc-remote.service
rm -f "$TMP_SVC"
c_ok "Panel service installed (User=$TARGET_USER)."

# --- 8. start services -------------------------------------------------------
sudo systemctl daemon-reload
sudo systemctl enable hid-gadget.service >/dev/null 2>&1 || true
sudo systemctl enable pc-remote.service  >/dev/null 2>&1 || true

if [[ "$NEED_REBOOT" -eq 1 ]]; then
    c_warn "config.txt changed — the USB gadget will only come up after a REBOOT."
else
    # The gadget is best (re)started on a fresh boot, but if the overlay was
    # already present, try to bring it up now.
    sudo systemctl restart hid-gadget.service || c_warn "hid-gadget didn't start — check the USB cable/port and 'journalctl -u hid-gadget'."
    sudo systemctl restart pc-remote.service  || true
fi

# --- summary -----------------------------------------------------------------
echo
c_ok "Done."
IP="$(command -v tailscale >/dev/null && tailscale ip -4 2>/dev/null | head -1 || true)"
[[ -z "$IP" ]] && IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
echo
echo "  Panel:  http://${IP:-<pi-ip>}:$REMOTE_PORT"
echo "  Config: $CFG_DIR/config.env"
echo "  Logs:   journalctl -u pc-remote -f"
echo
if [[ "$NEED_REBOOT" -eq 1 ]]; then
    c_warn "Reboot now to activate the USB gadget:  sudo reboot"
fi
if ! command -v tailscale >/dev/null; then
    c_info "Tailscale not found — to reach the panel remotely, install it (README, step 2)."
fi
